name: Parmar SSC Daily Downloader

on:
  workflow_dispatch:
  schedule:
    # UPDATED: Runs every 15 mins between 3:15 and 6:15 UTC (8:45 AM - 11:45 AM IST)
    - cron: '15,30,45 3 * * 1-6'
    - cron: '0,15,30,45 4 * * 1-6'
    - cron: '0,15,30,45 5 * * 1-6'
    - cron: '0,15 6 * * 1-6'

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    outputs:
      new_video_json: ${{ steps.downloader.outputs.new_video_json }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp requests
          sudo apt-get update && sudo apt-get install -y rclone jq

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf
        
      - name: Run Scraper and Downloader
        id: downloader
        env:
          YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}
        run: |
          python downloader.py

      - name: Update videos.json database
        id: update_videos
        if: fromJson(steps.downloader.outputs.new_video_json) != null
        run: |
          jq --argjson newVideo '${{ steps.downloader.outputs.new_video_json }}' '. + [$newVideo]' videos.json > temp.json && mv temp.json videos.json

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@github.com'
          # --- YEH LINE UPDATE HUI HAI ---
          git add videos.json schedule.json live.json
          # -----------------------------
          # Check if there are changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "feat: Update video library and schedule from $(date -u +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit."
          fi
